extend = "../../ruff.toml"
src = ["src"]

[lint.isort]
known-first-party = ["mb_workflow"]

[lint.flake8-type-checking]
runtime-evaluated-base-classes = [
    "pydantic.BaseModel",
    "pydantic.RootModel",
    "mb_workflow.d_lib.models.Model",
    "mb_workflow.d_lib.models.Payload",
    "mb_workflow.d_lib.models.Value",
]
